SELECT
    *
FROM
    AGENT_BANKING.CUSTIDINFO C
    LEFT JOIN AGENT_BANKING.REGINFO R
    ON C.CUST_ID = R.CUST_ID
WHERE
    C.NID_NO = :ITEM
    OR C.CON_MOB = :ITEM
    OR R.MPHONE = :ITEM
    OR R.CUST_ID = :ITEM