SELECT
    C.CUST_ID,
    C.NAME,
    C.NID_NO,
    C.DOB,
    C.EMAIL,
    C.FATHER_NAME,
    C.MOTHER_NAME,
    C.SPOUSE_NAME,
    R.CON_MOB,
    C.REG_DATE,
    R.MPHONE,
    C.PMPHONE,
    R.REG_STATUS,
    R.STATUS,
    C.CUST_ID_TYPE
FROM
    AGENT_BANKING.CUSTIDINFO C
    LEFT JOIN AGENT_BANKING.REGINFO R
    ON C.CUST_ID = R.CUST_ID
WHERE
    UPPER (C.NID_NO) LIKE UPPER (:ITEM)
    OR UPPER (C.CON_MOB) LIKE UPPER (:ITEM)
    OR UPPER (R.MPHONE) LIKE UPPER (:ITEM)
    OR UPPER (R.CUST_ID) LIKE UPPER (:ITEM)
    OR UPPER (C.NAME) LIKE UPPER (:ITEM) FETCH FIRST 25 ROWS ONLY