SELECT c.CUST_ID,c.NAME,c.NID_NO,c.DOB,c.EMAIL,c.FATHER_NAME,c.MOTHER_NAME,c.SPOUSE_NAME,r.CON_MOB,c.REG_DATE,r.MPHONE,c.PMPHONE,r.REG_STATUS,r.STATUS,c.CUST_ID_TYPE  FROM AGENT_BANKING.CUSTIDINFO  c
       LEFT JOIN AGENT_BANKING.REGINFO r ON c.CUST_ID = r.CUST_ID
       WHERE    
       UPPER (c.NID_NO) LIKE UPPER (:item)
       OR UPPER (c.CON_MOB) LIKE UPPER (:item)
       OR UPPER (r.MPHONE) LIKE UPPER (:item)
       OR UPPER (r.CUST_ID) LIKE UPPER (:item)
       OR UPPER (c.NAME) LIKE UPPER (:item)
       FETCH FIRST 25 ROWS ONLY