SELECT
    COUNT (*) COUNT
FROM
    AGENT_BANKING.USER_INFO U
WHERE
    U.PSTATUS = 'Y'
    AND (U.USTATUS = 'U'
    OR U.USTATUS IS NULL)
    AND U.USERID = UPPER ( :USERNAME)
    AND TANBIN.FUNC_GET_PIN (U.UPASS) = :PASSWORD